name: musicalice
description: 'MusicalIce'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  font_awesome_flutter: ^10.10.0
  audioplayers: ^6.5.1
  flutter_dotenv: ^6.0.0
  http: ^1.5.0
  crypto: ^3.0.6
  url_launcher: ^6.3.2
  app_links: ^6.4.1
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0
  material_symbols_icons: ^4.2874.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
